---
- hosts: all
  vars:
    packages:
      - software-properties-common
      - git
      - build-essential
      - supervisor
      - screen
      - tmux
      - python-pip
      - golang-go
      - python-twisted
      - netdata
      - ethereum
      - libdbus-1-dev
      - mesa-common-dev
      - nginx
      - apache2
      - php

  tasks:

  # apt-get packages required for all of the rest of this
  - name: Add apt repositories for ethereum
    apt_repository:
      repo: ppa:ethereum/ethereum
    become: yes

  - name: Add apt repositories for ethereum-dev
    apt_repository:
      repo: ppa:ethereum/ethereum-dev
    become: yes

  - name: Ansible apt install packages
    apt:
      pkg: "{{ packages }}"
      update_cache: true
      state: present
    become: yes

  # eth-proxy
  - name: ensure the eth-proxy user exists
    user:
      name: eth-proxy
      create_home: no
    become: yes

  - name: ensure the eth-proxy directory exists in /opt and that it is owned by the eth-proxy user
    file:
      path: /opt/eth-proxy
      state: directory
      owner: eth-proxy
      group: eth-proxy
    become: yes

  - name: checkout the git repo into the eth-proxy directory
    git:
      repo: 'https://github.com/Atrides/eth-proxy.git'
      dest: /opt/eth-proxy/
      force: yes
    become: yes
    become_user: eth-proxy

  - name: copy the configuration file into the eth-proxy directory
    copy:
      src: conf/eth-proxy.conf
      dest: /opt/eth-proxy/eth-proxy.conf
    become: yes
    become_user: eth-proxy

  - name: copy the configuration file into the supervisor directory
    copy:
      src: conf/supervisor/ethproxy.conf
      dest: /etc/supervisor/conf.d
    become: yes

  # ethminer
  - name: ensure the ethminer user exists
    user:
      name: ethminer
      groups: video
      create_home: no
    become: yes

  - name: checkout the git repo into the ethminer directory
    git:
      repo: 'https://github.com/ethereum-mining/ethminer.git'
      dest: /tmp/ethminer/
      force: yes

  - name: make the build directory
    file:
      path: /tmp/ethminer/build
      state: directory

  - name: configure the build for ethminer
    shell: cmake .. -DETHASHCUDA=OFF
    args:
      chdir: /tmp/ethminer/build

  - name: build and install ethminer
    shell: make install
    args:
      chdir: /tmp/ethminer/build
    become: yes

  - name: copy the configuration file into the supervisor directory
    copy:
      src: conf/supervisor/ethminer.conf
      dest: /etc/supervisor/conf.d
    become: yes

  - name: copy the swatchdog config to supervisor directory
    copy:
      src: conf/supervisor/swatchdog.conf
      dest: /etc/supervisor/conf.d
    become: yes

  - name: copy the swatchdogrc to supervisor directory
    copy:
      src: conf/supervisor/.swatchdogrc
      dest: /etc/supervisor/conf.d
    become: yes

  # ethereum full node
  #- name: copy the geth config to supervisor directory
  #  copy:
  #    src: conf/supervisor/geth.conf
  #    dest: /etc/supervisor/conf.d
  #  become: yes

  # ipfs
  - name: Download and untar ipfs
    unarchive:
      src: https://dist.ipfs.io/go-ipfs/v0.4.20/go-ipfs_v0.4.20_linux-amd64.tar.gz
      dest: /tmp
      remote_src: yes

  - name: install ipfs
    shell: ./install.sh
    args:
      chdir: /tmp/go-ipfs
    become: yes

  - name: init ipfs
    shell: ipfs init
    args:
      creates: /home/jason/.ipfs

  #- name: copy the ipfs config to supervisor directory
  #  copy:
  #    src: conf/supervisor/ipfs.conf
  #    dest: /etc/supervisor/conf.d
  #  become: yes

  # golem
  #- name: copy the golem config to supervisor directory
  #  copy:
  #    src: conf/supervisor/golem.conf
  #    dest: /etc/supervisor/conf.d
  #  become: yes
  # tor
